import type { Banner, Category, DeliverySetting, Product, Profile } from '@/types';

const now = () => new Date().toISOString();

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-fv', name: 'Fruits & Vegetables', slug: 'fruits-vegetables', icon_name: 'Apple', sort_order: 1, is_active: true, created_at: now() },
  { id: 'cat-db', name: 'Dairy & Bakery', slug: 'dairy-bakery', icon_name: 'Milk', sort_order: 2, is_active: true, created_at: now() },
  { id: 'cat-gs', name: 'Grains & Staples', slug: 'grains-staples', icon_name: 'Wheat', sort_order: 3, is_active: true, created_at: now() },
  { id: 'cat-sb', name: 'Snacks & Beverages', slug: 'snacks-beverages', icon_name: 'Cookie', sort_order: 4, is_active: true, created_at: now() },
  { id: 'cat-pc', name: 'Personal Care', slug: 'personal-care', icon_name: 'Spa', sort_order: 5, is_active: true, created_at: now() },
  { id: 'cat-hh', name: 'Household Items', slug: 'household-items', icon_name: 'Home', sort_order: 6, is_active: true, created_at: now() },
];

type ProductSeed = Omit<Product, 'category' | 'created_at'> & { created_at?: string };

const productsRaw: ProductSeed[] = [
  { id: 'p1', category_id: 'cat-fv', name: 'Fresh Red Apples', slug: 'fresh-red-apples', description: 'Crisp, sweet red apples hand-picked for freshness.', price: 180, mrp: 220, unit: 'kg', stock_quantity: 40, brand: 'Farm Fresh', image_url: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.5 },
  { id: 'p2', category_id: 'cat-fv', name: 'Bananas', slug: 'bananas', description: 'Ripe yellow bananas, rich in potassium.', price: 50, mrp: 60, unit: 'dozen', stock_quantity: 60, brand: 'Farm Fresh', image_url: 'https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.2 },
  { id: 'p3', category_id: 'cat-fv', name: 'Tomatoes', slug: 'tomatoes', description: 'Farm-fresh ripe tomatoes, perfect for curries and salads.', price: 40, mrp: 55, unit: 'kg', stock_quantity: 35, brand: 'Local Farm', image_url: 'https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.0 },
  { id: 'p4', category_id: 'cat-fv', name: 'Onions', slug: 'onions', description: 'Fresh onions, a kitchen essential.', price: 35, mrp: 45, unit: 'kg', stock_quantity: 80, brand: 'Local Farm', image_url: 'https://images.pexels.com/photos/1306554/pexels-photo-1306554.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.1 },
  { id: 'p5', category_id: 'cat-fv', name: 'Green Capsicum', slug: 'green-capsicum', description: 'Crunchy green bell peppers.', price: 60, mrp: 80, unit: 'kg', stock_quantity: 25, brand: 'Farm Fresh', image_url: 'https://images.pexels.com/photos/1596077/pexels-photo-1596077.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.3 },
  { id: 'p6', category_id: 'cat-fv', name: 'Carrots', slug: 'carrots', description: 'Fresh orange carrots, great for salads and juices.', price: 45, mrp: 60, unit: 'kg', stock_quantity: 30, brand: 'Local Farm', image_url: 'https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.2 },
  { id: 'p7', category_id: 'cat-db', name: 'Amul Full Cream Milk', slug: 'amul-full-cream-milk', description: 'Fresh full cream milk, 1 litre pouch.', price: 68, mrp: 72, unit: 'litre', stock_quantity: 50, brand: 'Amul', image_url: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.6 },
  { id: 'p8', category_id: 'cat-db', name: 'Brown Bread', slug: 'brown-bread', description: 'Whole wheat brown bread loaf, freshly baked.', price: 45, mrp: 50, unit: 'pack', stock_quantity: 20, brand: 'Modern Bakery', image_url: 'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.4 },
  { id: 'p9', category_id: 'cat-db', name: 'Paneer', slug: 'paneer', description: 'Fresh soft paneer, 200g pack.', price: 90, mrp: 110, unit: 'pack', stock_quantity: 15, brand: 'Amul', image_url: 'https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.5 },
  { id: 'p10', category_id: 'cat-db', name: 'Butter', slug: 'butter', description: 'Salted butter, 100g pack.', price: 52, mrp: 55, unit: 'pack', stock_quantity: 18, brand: 'Amul', image_url: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.3 },
  { id: 'p11', category_id: 'cat-db', name: 'Eggs', slug: 'eggs', description: 'Farm fresh brown eggs, pack of 6.', price: 60, mrp: 72, unit: 'pack', stock_quantity: 40, brand: 'Farm Fresh', image_url: 'https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.5 },
  { id: 'p12', category_id: 'cat-gs', name: 'Basmati Rice', slug: 'basmati-rice', description: 'Premium long-grain basmati rice, 1kg.', price: 120, mrp: 150, unit: 'kg', stock_quantity: 50, brand: 'India Gate', image_url: 'https://images.pexels.com/photos/743251/pexels-photo-743251.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.7 },
  { id: 'p13', category_id: 'cat-gs', name: 'Toor Dal', slug: 'toor-dal', description: 'Yellow split pigeon peas, 1kg.', price: 130, mrp: 160, unit: 'kg', stock_quantity: 45, brand: 'Tata Sampann', image_url: 'https://images.pexels.com/photos/1393382/pexels-photo-1393382.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.3 },
  { id: 'p14', category_id: 'cat-gs', name: 'Wheat Flour', slug: 'wheat-flour', description: 'Whole wheat atta, 2kg pack.', price: 85, mrp: 95, unit: 'pack', stock_quantity: 60, brand: 'Aashirvaad', image_url: 'https://images.pexels.com/photos/743251/pexels-photo-743251.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.4 },
  { id: 'p15', category_id: 'cat-gs', name: 'Sunflower Oil', slug: 'sunflower-oil', description: 'Refined sunflower cooking oil, 1 litre.', price: 165, mrp: 190, unit: 'litre', stock_quantity: 30, brand: 'Fortune', image_url: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.2 },
  { id: 'p16', category_id: 'cat-gs', name: 'Sugar', slug: 'sugar', description: 'Refined white sugar, 1kg.', price: 48, mrp: 52, unit: 'kg', stock_quantity: 70, brand: 'Madhur', image_url: 'https://images.pexels.com/photos/2664216/pexels-photo-2664216.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.0 },
  { id: 'p17', category_id: 'cat-sb', name: 'Lays Classic Salted', slug: 'lays-classic-salted', description: 'Crispy salted potato chips, 52g.', price: 20, mrp: 25, unit: 'pack', stock_quantity: 100, brand: 'Lays', image_url: 'https://images.pexels.com/photos/7874593/pexels-photo-7874593.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.4 },
  { id: 'p18', category_id: 'cat-sb', name: 'Coca-Cola', slug: 'coca-cola', description: 'Refreshing cola, 750ml bottle.', price: 40, mrp: 45, unit: 'pack', stock_quantity: 80, brand: 'Coca-Cola', image_url: 'https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.3 },
  { id: 'p19', category_id: 'cat-sb', name: 'Dark Chocolate', slug: 'dark-chocolate', description: '70% dark chocolate bar, 80g.', price: 120, mrp: 150, unit: 'pack', stock_quantity: 25, brand: 'Amul', image_url: 'https://images.pexels.com/photos/65882/chocolate-dark-coffee-confiserie-65882.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.6 },
  { id: 'p20', category_id: 'cat-sb', name: 'Green Tea', slug: 'green-tea', description: 'Green tea bags, pack of 25.', price: 140, mrp: 180, unit: 'pack', stock_quantity: 35, brand: 'Lipton', image_url: 'https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.2 },
  { id: 'p21', category_id: 'cat-sb', name: 'Mixed Nuts', slug: 'mixed-nuts', description: 'Roasted salted mixed nuts, 200g.', price: 220, mrp: 260, unit: 'pack', stock_quantity: 20, brand: 'Act II', image_url: 'https://images.pexels.com/photos/1295572/pexels-photo-1295572.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.5 },
  { id: 'p22', category_id: 'cat-pc', name: 'Shampoo', slug: 'shampoo', description: 'Anti-dandruff shampoo, 340ml.', price: 175, mrp: 220, unit: 'pack', stock_quantity: 40, brand: 'Head & Shoulders', image_url: 'https://images.pexels.com/photos/3997383/pexels-photo-3997383.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.3 },
  { id: 'p23', category_id: 'cat-pc', name: 'Toothpaste', slug: 'toothpaste', description: 'Mint freshness toothpaste, 150g.', price: 95, mrp: 110, unit: 'pack', stock_quantity: 60, brand: 'Colgate', image_url: 'https://images.pexels.com/photos/33832/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.4 },
  { id: 'p24', category_id: 'cat-pc', name: 'Bathing Soap', slug: 'bathing-soap', description: 'Moisturising bathing soap, pack of 3.', price: 105, mrp: 120, unit: 'pack', stock_quantity: 50, brand: 'Dove', image_url: 'https://images.pexels.com/photos/4202325/pexels-photo-4202325.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.5 },
  { id: 'p25', category_id: 'cat-pc', name: 'Hand Wash', slug: 'hand-wash', description: 'Germ protection hand wash, 200ml.', price: 110, mrp: 130, unit: 'pack', stock_quantity: 30, brand: 'Dettol', image_url: 'https://images.pexels.com/photos/3997383/pexels-photo-3997383.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.2 },
  { id: 'p26', category_id: 'cat-hh', name: 'Dishwash Gel', slug: 'dishwash-gel', description: 'Lemon dishwash gel, 750ml.', price: 85, mrp: 105, unit: 'pack', stock_quantity: 45, brand: 'Vim', image_url: 'https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.3 },
  { id: 'p27', category_id: 'cat-hh', name: 'Laundry Detergent', slug: 'laundry-detergent', description: 'Front-load detergent powder, 2kg.', price: 245, mrp: 300, unit: 'pack', stock_quantity: 35, brand: 'Surf Excel', image_url: 'https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: true, is_out_of_stock: false, rating: 4.4 },
  { id: 'p28', category_id: 'cat-hh', name: 'Toilet Cleaner', slug: 'toilet-cleaner', description: 'Disinfectant toilet cleaner, 500ml.', price: 75, mrp: 90, unit: 'pack', stock_quantity: 28, brand: 'Harpic', image_url: 'https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.1 },
  { id: 'p29', category_id: 'cat-hh', name: 'Garbage Bags', slug: 'garbage-bags', description: 'Biodegradable garbage bags, pack of 30.', price: 120, mrp: 150, unit: 'pack', stock_quantity: 0, brand: 'Glad', image_url: 'https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: true, rating: 3.9 },
  { id: 'p30', category_id: 'cat-hh', name: 'Floor Cleaner', slug: 'floor-cleaner', description: 'Citrus floor cleaner, 1 litre.', price: 95, mrp: 115, unit: 'pack', stock_quantity: 22, brand: 'Lizol', image_url: 'https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg?auto=compress&cs=tinysrgb&w=600', is_featured: false, is_out_of_stock: false, rating: 4.2 },
];

export const SEED_PRODUCTS: Product[] = productsRaw.map((p) => ({ ...p, created_at: now() }));

export const SEED_BANNERS: Banner[] = [
  { id: 'b1', title: 'Fresh Fruits & Veggies', subtitle: 'Farm-fresh produce delivered to your door. Up to 20% off.', image_url: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=1200', cta_label: 'Shop Fresh', cta_link: '/category/fruits-vegetables', sort_order: 1, is_active: true, created_at: now() },
  { id: 'b2', title: 'Stock Up Your Pantry', subtitle: 'Grains, oils & staples at the best prices. Free delivery over 499.', image_url: 'https://images.pexels.com/photos/4198015/pexels-photo-4198015.jpeg?auto=compress&cs=tinysrgb&w=1200', cta_label: 'Shop Staples', cta_link: '/category/grains-staples', sort_order: 2, is_active: true, created_at: now() },
  { id: 'b3', title: 'Snack Time Favourites', subtitle: 'Chips, chocolates & beverages to power your day.', image_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1200', cta_label: 'Shop Snacks', cta_link: '/category/snacks-beverages', sort_order: 3, is_active: true, created_at: now() },
];

export const SEED_DELIVERY: DeliverySetting[] = [
  { id: 'd1', pincode: '110001', area_name: 'Central Delhi', delivery_charge: 30, min_order_for_free_delivery: 499, is_active: true, created_at: now() },
  { id: 'd2', pincode: '110002', area_name: 'Karol Bagh', delivery_charge: 40, min_order_for_free_delivery: 499, is_active: true, created_at: now() },
];

export const SEED_ADMIN: Profile & { password: string } = {
  id: 'user-admin',
  full_name: 'Store Admin',
  phone: '9999999999',
  email: 'admin@allinone.shop',
  app_role: 'admin',
  created_at: now(),
  password: 'admin123',
};
